# Generated by Django 5.0.6 on 2024-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
