# Generated by Django 5.0 on 2024-06-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_suppliers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
