# Generated by Django 5.0 on 2024-06-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_delete_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=200)),
                ('ownername', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('approval', models.IntegerField()),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
