# Generated by Django 5.0 on 2024-06-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
