# Generated by Django 5.0 on 2024-06-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.BigIntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
    ]
