# Generated by Django 5.0 on 2024-06-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
