# Generated by Django 5.0 on 2024-06-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
