# Generated by Django 5.0 on 2024-06-15 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0020_remove_order_product_remove_order_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_address', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_deliver', models.DateTimeField()),
                ('payments', models.CharField(max_length=50)),
                ('payment_id', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierid', to='myadmin.suppliers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productid', to='myadmin.product')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
