# Generated by Django 5.0 on 2024-06-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0021_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
