# Generated by Django 5.0 on 2024-06-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0025_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
